# Generated by Django 5.2.5 on 2025-10-06 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminDashboardStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_hospitals', models.IntegerField(default=0)),
                ('total_doctors', models.IntegerField(default=0)),
                ('total_users', models.IntegerField(default=0)),
                ('total_appointments', models.IntegerField(default=0)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Admin Dashboard Statistics',
            },
        ),
    ]
