# Generated by Django 5.2.5 on 2025-10-09 16:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0002_adminactivity_adminprofile'),
        ('doctor', '0006_appointmentslot_doctor'),
        ('hospital', '0002_hospital_ambulance_number_hospital_description_and_more'),
        ('userapp', '0012_review_guest_name_alter_review_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('notification_type', models.CharField(choices=[('user_registration', 'User Registration'), ('doctor_registration', 'Doctor Registration'), ('hospital_registration', 'Hospital Registration'), ('system_alert', 'System Alert'), ('new_appointment', 'New Appointment')], max_length=50)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('related_doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='doctor.doctor')),
                ('related_hospital', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hospital.hospital')),
                ('related_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='userapp.userregistration')),
            ],
            options={
                'verbose_name_plural': 'Admin Notifications',
                'ordering': ['-created_at'],
            },
        ),
    ]
