# Generated by Django 5.2.5 on 2025-09-30 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0008_feedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='is_approved',
            field=models.BooleanField(default=True),
        ),
    ]
