# Generated by Django 5.2.5 on 2025-10-07 05:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0006_appointmentslot_doctor'),
        ('hospital', '0002_hospital_ambulance_number_hospital_description_and_more'),
        ('userapp', '0009_alter_feedback_is_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='doctor.doctor'),
        ),
        migrations.AddField(
            model_name='notification',
            name='hospital',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hospital.hospital'),
        ),
    ]
