# Generated by Django 5.2.5 on 2025-10-08 04:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0006_appointmentslot_doctor'),
        ('hospital', '0002_hospital_ambulance_number_hospital_description_and_more'),
        ('userapp', '0010_notification_doctor_notification_hospital'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')])),
                ('comment', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='doctor.doctor')),
                ('hospital', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hospital.hospital')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userapp.userregistration')),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('doctor__isnull', False), ('hospital__isnull', True)), models.Q(('doctor__isnull', True), ('hospital__isnull', False)), _connector='OR'), name='review_doctor_or_hospital')],
            },
        ),
    ]
