# Generated by Django 5.2.5 on 2025-11-02 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0015_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='userregistration',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='user_images/'),
        ),
    ]
