# Generated by Django 5.2.5 on 2025-11-02 19:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0017_emergencyqrcode'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmergencyAccessCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_code', models.CharField(max_length=8, unique=True)),
                ('qr_code', models.CharField(max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('last_accessed', models.DateTimeField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='userapp.userregistration')),
            ],
        ),
        migrations.DeleteModel(
            name='EmergencyQRCode',
        ),
    ]
