# Generated by Django 5.2.5 on 2025-09-21 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0002_doctor_bio_doctor_education_doctor_experience_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='twitter',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
