# Generated by Django 5.2.5 on 2025-09-22 05:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0003_doctor_twitter'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctor',
            old_name='education',
            new_name='qualifications',
        ),
    ]
