# Generated by Django 5.2.5 on 2025-09-28 16:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0005_appointmentslot'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointmentslot',
            name='doctor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='doctor.doctor'),
        ),
    ]
